// <auto-generated />
using System;
using EkoMon.DomainModel.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EkoMon.DomainModel.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20230513114744_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EkoMon.DomainModel.Db.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "",
                            Latitude = 50.449538255595499,
                            Longitude = 30.525422556705447,
                            Title = "місто Київ"
                        },
                        new
                        {
                            Id = 2,
                            Address = "",
                            Latitude = 50.454813999999999,
                            Longitude = 30.635262999999998,
                            Title = "Київський автомобільний ремонтний завод"
                        },
                        new
                        {
                            Id = 3,
                            Address = "",
                            Latitude = 50.471031886528294,
                            Longitude = 30.512898573607249,
                            Title = "Станція для визначення рівня забруднення атмосферного повітря"
                        });
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.LocationParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int>("ParameterId")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ParameterId");

                    b.ToTable("LocationParameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocationId = 3,
                            ParameterId = 1,
                            Value = 2.5
                        },
                        new
                        {
                            Id = 2,
                            LocationId = 3,
                            ParameterId = 2,
                            Value = 3.1000000000000001
                        },
                        new
                        {
                            Id = 3,
                            LocationId = 3,
                            ParameterId = 3,
                            Value = 5.7000000000000002
                        },
                        new
                        {
                            Id = 4,
                            LocationId = 3,
                            ParameterId = 4,
                            Value = 5.5
                        },
                        new
                        {
                            Id = 5,
                            LocationId = 3,
                            ParameterId = 5,
                            Value = 57.700000000000003
                        },
                        new
                        {
                            Id = 6,
                            LocationId = 3,
                            ParameterId = 6,
                            Value = 1006.7
                        },
                        new
                        {
                            Id = 7,
                            LocationId = 3,
                            ParameterId = 7,
                            Value = 13.0
                        });
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Parameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "PM1",
                            UnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            Title = "PM2.5",
                            UnitId = 1
                        },
                        new
                        {
                            Id = 3,
                            Title = "PM10",
                            UnitId = 1
                        },
                        new
                        {
                            Id = 4,
                            Title = "Температура",
                            UnitId = 2
                        },
                        new
                        {
                            Id = 5,
                            Title = "Відносна вологість",
                            UnitId = 3
                        },
                        new
                        {
                            Id = 6,
                            Title = "Атмосферний тиск",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 7,
                            Title = "AQI PM2.5"
                        });
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "мкг/м³"
                        },
                        new
                        {
                            Id = 2,
                            Title = "°C"
                        },
                        new
                        {
                            Id = 3,
                            Title = "%"
                        },
                        new
                        {
                            Id = 4,
                            Title = "гПа"
                        });
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.LocationParameter", b =>
                {
                    b.HasOne("EkoMon.DomainModel.Db.Location", "Location")
                        .WithMany("LocationParameters")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EkoMon.DomainModel.Db.Parameter", "Parameter")
                        .WithMany("LocationParameters")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Parameter", b =>
                {
                    b.HasOne("EkoMon.DomainModel.Db.Unit", "Unit")
                        .WithMany("Parameters")
                        .HasForeignKey("UnitId");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Location", b =>
                {
                    b.Navigation("LocationParameters");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Parameter", b =>
                {
                    b.Navigation("LocationParameters");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Unit", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
