// <auto-generated />
using System;
using EkoMon.DomainModel.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EkoMon.DomainModel.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20230513172011_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EkoMon.DomainModel.Db.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Стан повітря"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Стан водних ресурсів"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Стан ґрунтів"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Рівень радіації"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Відходи"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Економічний стан"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Стан здоров’я населення"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Енергетичний стан"
                        });
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.LocationParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int>("ParameterId")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ParameterId");

                    b.ToTable("LocationParameters");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitId");

                    b.ToTable("Parameters");

                    b.HasData(
                        new
                        {
                            Id = 34,
                            CategoryId = 1,
                            Title = "Індекс якості повітря",
                            Type = 1
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            Title = "Індекс забрудненості води",
                            Type = 1
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Title = "Бал бонітету для складового грунту",
                            Type = 1
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            Title = "Ймовірність критичної події",
                            Type = 1
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Title = "Ризики радіаційного впливу на довкілля та здоров'я населення",
                            Type = 1
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 6,
                            Title = "Індекс промислової продукції",
                            Type = 1
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 6,
                            Title = "Індекс обсягу сільськогосподарського виробництва",
                            Type = 1
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 6,
                            Title = "Індекс будівельної продукції",
                            Type = 1
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 6,
                            Title = "Індекс споживчих цін",
                            Type = 1
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 6,
                            Title = "Індекс цін виробників промислової продукції",
                            Type = 1
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 7,
                            Title = "Ризики захворювання",
                            Type = 1
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 7,
                            Title = "Прогноз захворювання",
                            Type = 1
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 7,
                            Title = "Прогноз тривалості життя",
                            Type = 1,
                            UnitId = 13
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 8,
                            Title = "Середні обсяги споживання за місяць та рік",
                            Type = 1
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 8,
                            Title = "Енергоефективність будівлі або виробництва",
                            Type = 1
                        },
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Title = "Вміст пилу",
                            Type = 0,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Title = "Двоокис азоту (NO2)",
                            Type = 0,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Title = "Двоокис сірки (SO2)",
                            Type = 0,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Title = "Оксид вуглецю",
                            Type = 0,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Title = "Формальдегід (H2CO)",
                            Type = 0,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Title = "Свинець",
                            Type = 0,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Title = "Бенз(а)пірен",
                            Type = 0,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Title = "Показники епідемічної безпеки (мікробіологічні, паразитарні)",
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Title = "Санітарно-хімічні (органолептичні, фізико-хімічні, санітарно-токсикологічні)",
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Title = "Радіаційні показники",
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Title = "Гумус",
                            Type = 0,
                            UnitId = 2
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Title = "Рухомі сполуки фосфору (P2O5)",
                            Type = 0,
                            UnitId = 3
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Title = "Рухомі сполуки калію (K2O)",
                            Type = 0,
                            UnitId = 3
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Title = "Засоленість",
                            Type = 0,
                            UnitId = 4
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Title = "Солонцюватість",
                            Type = 0,
                            UnitId = 4
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Title = "Забруднення хімічними речовинами",
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Title = "pH",
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Title = "Концентрація продуктів ядерного розпаду з коротким часом життя",
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Title = "Концентрація продуктів ядерного розпаду з середнім часом життя",
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Title = "Клас небезпеки",
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            Title = "Токсичність",
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            Title = "Склад (вміст речовин)",
                            Type = 0
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Title = "Маса або об’єм",
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Title = "Валовий внутрішній продукт",
                            Type = 0
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 6,
                            Title = "Вантажообіг",
                            Type = 0,
                            UnitId = 5
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 6,
                            Title = "Пасажирообіг",
                            Type = 0,
                            UnitId = 6
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 6,
                            Title = "Експорт товарів та послуг",
                            Type = 0,
                            UnitId = 7
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 6,
                            Title = "Імпорт товарів та послуг",
                            Type = 0,
                            UnitId = 7
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 6,
                            Title = "Заробітна плата",
                            Type = 0,
                            UnitId = 8
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 7,
                            Title = "Обсяги використання води",
                            Type = 0,
                            UnitId = 9
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 7,
                            Title = "Електроенергія",
                            Type = 0,
                            UnitId = 10
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 7,
                            Title = "Газ",
                            Type = 0,
                            UnitId = 11
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 7,
                            Title = "Теплова енергія за кожен місяць",
                            Type = 0,
                            UnitId = 12
                        });
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "мг/м³"
                        },
                        new
                        {
                            Id = 2,
                            Title = "%"
                        },
                        new
                        {
                            Id = 3,
                            Title = "мг/кг"
                        },
                        new
                        {
                            Id = 4,
                            Title = "г/л"
                        },
                        new
                        {
                            Id = 5,
                            Title = "тонн"
                        },
                        new
                        {
                            Id = 6,
                            Title = "чол."
                        },
                        new
                        {
                            Id = 7,
                            Title = "млн. дол."
                        },
                        new
                        {
                            Id = 8,
                            Title = "грн."
                        },
                        new
                        {
                            Id = 9,
                            Title = "м³"
                        },
                        new
                        {
                            Id = 10,
                            Title = "кВт·год"
                        },
                        new
                        {
                            Id = 11,
                            Title = "м³"
                        },
                        new
                        {
                            Id = 12,
                            Title = "Гкал"
                        },
                        new
                        {
                            Id = 13,
                            Title = "роки"
                        });
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.LocationParameter", b =>
                {
                    b.HasOne("EkoMon.DomainModel.Db.Location", "Location")
                        .WithMany("LocationParameters")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EkoMon.DomainModel.Db.Parameter", "Parameter")
                        .WithMany("LocationParameters")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Parameter", b =>
                {
                    b.HasOne("EkoMon.DomainModel.Db.Category", "Category")
                        .WithMany("Parameters")
                        .HasForeignKey("CategoryId");

                    b.HasOne("EkoMon.DomainModel.Db.Unit", "Unit")
                        .WithMany("Parameters")
                        .HasForeignKey("UnitId");

                    b.Navigation("Category");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Category", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Location", b =>
                {
                    b.Navigation("LocationParameters");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Parameter", b =>
                {
                    b.Navigation("LocationParameters");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Unit", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
