// <auto-generated />
using System;
using EkoMon.DomainModel.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EkoMon.DomainModel.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EkoMon.DomainModel.Db.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Стан повітря"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Стан водних ресурсів"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Стан ґрунтів"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Рівень радіації"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Відходи"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Економічний стан"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Стан здоров’я населення"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Енергетичний стан"
                        });
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Area")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.LocationParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int>("ParameterId")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ParameterId");

                    b.ToTable("LocationParameters");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<double?>("Koef")
                        .HasColumnType("double precision");

                    b.Property<double?>("Limit")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitId");

                    b.ToTable("Parameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Limit = 5.0,
                            Title = "Вміст пилу",
                            UnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Limit = 0.059999999999999998,
                            Title = "Азоту оксид",
                            UnitId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Limit = 0.10000000000000001,
                            Title = "Амонію сульфат",
                            UnitId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Limit = 3.0,
                            Title = "Оксид вуглецю",
                            UnitId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Limit = 0.0030000000000000001,
                            Title = "Формальдегід",
                            UnitId = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Limit = 0.00029999999999999997,
                            Title = "Свинець",
                            UnitId = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Limit = 0.0001,
                            Title = "Бенз(а)пірен",
                            UnitId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Limit = 100.0,
                            Title = "Мікробне число"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Limit = 3.0,
                            Title = "Колі-індекс"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Limit = 300.0,
                            Title = "Колі-титр",
                            UnitId = 2
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Limit = 7.0,
                            Title = "Твердість",
                            UnitId = 3
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Limit = 1000.0,
                            Title = "Щільний осадок",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Limit = 0.29999999999999999,
                            Title = "Залізо",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Limit = 500.0,
                            Title = "Сульфати",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Limit = 350.0,
                            Title = "Хлориди",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Limit = 1.0,
                            Title = "Мідь",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Limit = 5.0,
                            Title = "Марганець",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Limit = 0.10000000000000001,
                            Title = "Фосфати",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Limit = 10.0,
                            Title = "Нітрати",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Limit = 0.002,
                            Title = "Нітрити",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Limit = 1.5,
                            Title = "Фтор",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Limit = 0.029999999999999999,
                            Title = "Свинець",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Limit = 0.050000000000000003,
                            Title = "Миш’як",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Limit = 0.0050000000000000001,
                            Title = "Ртуть",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Limit = 0.10000000000000001,
                            Title = "Ціаніди",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Limit = 0.10000000000000001,
                            Title = "Алюміній",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            Limit = 3.5,
                            Title = "Молібден",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Limit = 0.001,
                            Title = "Селен",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            Limit = 0.69999999999999996,
                            Title = "Стронцій",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            Limit = 0.00020000000000000001,
                            Title = "Берилій",
                            UnitId = 4
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            Limit = 8.0,
                            Title = "pH"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Limit = 0.02,
                            Title = "Бенз(а)пірен",
                            UnitId = 5
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            Limit = 0.29999999999999999,
                            Title = "Бензол",
                            UnitId = 5
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            Limit = 1500.0,
                            Title = "Марганець",
                            UnitId = 5
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            Limit = 2.1000000000000001,
                            Title = "Ртуть",
                            UnitId = 5
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Limit = 32.0,
                            Title = "Свинець",
                            UnitId = 5
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            Limit = 160.0,
                            Title = "Сірка",
                            UnitId = 5
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 3,
                            Limit = 0.40000000000000002,
                            Title = "Сірководень",
                            UnitId = 5
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 3,
                            Limit = 1.5,
                            Title = "Кадмій",
                            UnitId = 5
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 3,
                            Limit = 130.0,
                            Title = "Нітрати",
                            UnitId = 5
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Title = "Концентрація продуктів ядерного розпаду",
                            UnitId = 6
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            Koef = 0.80000000000000004,
                            Title = "Відходи виробництва",
                            UnitId = 7
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            Koef = 0.90000000000000002,
                            Title = "Гірничі породи",
                            UnitId = 7
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            Koef = 0.69999999999999996,
                            Title = "Залишкові продукти первинної обробки сировини",
                            UnitId = 7
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            Koef = 0.59999999999999998,
                            Title = "Новоутворені речовини та їх суміші",
                            UnitId = 7
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            Koef = 0.5,
                            Title = "Залишкові продукти сільськогосподарського виробництва",
                            UnitId = 7
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            Koef = 0.59999999999999998,
                            Title = "Бракована та некондиційна продукція",
                            UnitId = 7
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            Koef = 0.40000000000000002,
                            Title = "Неідентифікована продукція",
                            UnitId = 7
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            Koef = 0.29999999999999999,
                            Title = "Відходи споживання",
                            UnitId = 7
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            Koef = 0.20000000000000001,
                            Title = "Побутові відходи",
                            UnitId = 7
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 5,
                            Koef = 0.69999999999999996,
                            Title = "Осади очисних споруд",
                            UnitId = 7
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 5,
                            Koef = 0.80000000000000004,
                            Title = "Залишки від медичного та ветеринарного обслуговування",
                            UnitId = 7
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 5,
                            Koef = 0.59999999999999998,
                            Title = "Залишкові продукти інших видів діяльності",
                            UnitId = 7
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 5,
                            Koef = 1.0,
                            Title = "Радіоактивні відходи",
                            UnitId = 7
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 6,
                            Title = "Експорт товарів та послуг",
                            UnitId = 8
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 6,
                            Title = "Імпорт товарів та послуг",
                            UnitId = 8
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 6,
                            Title = "Заробітна плата",
                            UnitId = 8
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 7,
                            Title = "Кількість людей",
                            UnitId = 9
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 7,
                            Title = "Кількість інвалідів",
                            UnitId = 9
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 7,
                            Title = "Кількість хронічних хвороб",
                            UnitId = 9
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 8,
                            Title = "Обсяги використання води",
                            UnitId = 10
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 8,
                            Title = "Обсяги використання електроенергії",
                            UnitId = 11
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 8,
                            Title = "Обсяги використання газу",
                            UnitId = 10
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 8,
                            Title = "Обсяги використання теплової енергії",
                            UnitId = 11
                        });
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "мг/м³"
                        },
                        new
                        {
                            Id = 2,
                            Title = "мл"
                        },
                        new
                        {
                            Id = 3,
                            Title = "мг/екв/л"
                        },
                        new
                        {
                            Id = 4,
                            Title = "мг/л"
                        },
                        new
                        {
                            Id = 5,
                            Title = "мг/кг"
                        },
                        new
                        {
                            Id = 6,
                            Title = "нЗв/год"
                        },
                        new
                        {
                            Id = 7,
                            Title = "кг/день"
                        },
                        new
                        {
                            Id = 8,
                            Title = "тис. грн"
                        },
                        new
                        {
                            Id = 9,
                            Title = "чол."
                        },
                        new
                        {
                            Id = 10,
                            Title = "м³"
                        },
                        new
                        {
                            Id = 11,
                            Title = "кВт·год"
                        });
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.LocationParameter", b =>
                {
                    b.HasOne("EkoMon.DomainModel.Db.Location", "Location")
                        .WithMany("LocationParameters")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EkoMon.DomainModel.Db.Parameter", "Parameter")
                        .WithMany("LocationParameters")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Parameter", b =>
                {
                    b.HasOne("EkoMon.DomainModel.Db.Category", "Category")
                        .WithMany("Parameters")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EkoMon.DomainModel.Db.Unit", "Unit")
                        .WithMany("Parameters")
                        .HasForeignKey("UnitId");

                    b.Navigation("Category");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Category", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Location", b =>
                {
                    b.Navigation("LocationParameters");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Parameter", b =>
                {
                    b.Navigation("LocationParameters");
                });

            modelBuilder.Entity("EkoMon.DomainModel.Db.Unit", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
